(function(){
    angular.module('app',[
        'ngRoute',
        'ui.bootstrap',
        'LocalStorageModule',
        'app.base',
        'app.nav',
        'app.configBtn',
        'app.systemConfig',
        'app.dataShow',
        'app.infoConfig',
        'app.meter'
    ])
})();