(function(){
    angular.module('app',[
        'ngRoute',
        'app.base',
        'app.nav',
        'app.configBtn',
        'app.systemConfig',
        'app.dataShow',
        'app.infoConfig'
    ])
})();